openapi: 3.0.2
info:
  description: >-
    This API is meant for provisioning resources in a target Cloud Environment in a vendor-agnostic fashion. By
    implementing this API, vendors make it possible to automatically provision accounts via ATAT.

    ## Portfolios

    Portfolios represent a logical container for a set of cloud resources which are paid for by a Task Order and its
    CLIN(s). The term is meant to be agnostic across CSPs. A Portfolio can be thought of as an account at the root of a 
    hierarchy. ATAT does not dictate structure within a Portfolio. Once a Portfolio has been provisioned a Mission Owner 
    is free to organize and secure resources to satisfy mission requirements.

    ## Task Orders

    Portfolios contain one or more *Task Orders* (TO), which in turn contain or more or *Contract Line Item Number*
    (CLINs). Each have separate Periods of Performance (PoP) dates; CLIN PoP dates will be within the time frames of
    the Task Order in which they belong.

    ## Cost reporting

    Provisioned resources incur costs with participating CSPs. Costs related to provisioned resources can
    be attributed to specific CLINs. Actual and forecasted CSP costs can be reported by CLIN.
  version: 0.3.0
  title: ATAT CSP API
  contact:
    email: atat-dev+provisioning_api@ccpo.mil
tags:
  - name: access
    description: >-
      Operations to manage access to provisioned Portfolios
  - name: cost
    description: >-
      Operations to query for actual and forecasted costs
  - name: provisioning
    description: >-
      Operations to manage provisioned Portfolios
paths:
  '/portfolios':
    post:
      tags:
        - provisioning
      summary: Adds a new Portfolio
      security:
        - oidc: [write:portfolio]
      description: Adds a new Portfolio to be provisioned, including Task Orders and Operators. Once provisioned, Operators can log in to the CSP and begin using provisioned resources and services, funded by the provided Task Order(s). See [#/info/description](#/info/description) and [#/components/schemas](#/components/schemas) for details of these constructs.
      operationId: addPortfolio
      parameters:
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
        - name: X-Provision-Deadline
          description: >-
            Deadline by which the ATAT client expects the Portfolio provisioning process to be complete. Actual values will not be dictated
            by this specification.
          in: header
          schema:
            type: string
            format: date-time
      requestBody:
        description: A new Portfolio
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Portfolio'
      responses:
        '200':
          description: Portfolio fully provisioned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Portfolio'
        '202':
          description: Portfolio provisioning request has been accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisioningStatus'
          headers:
            Location:
              description: Endpoint which ATAT should poll to receive status updates for this provisioning job
              schema:
                type: string
                example: "https://csp.com/atat/provisioning/123456789/status"
        '400':
          description: Invalid input
  '/portfolios/{portfolioId}':
    get:
      tags:
        - provisioning
      summary: Gets an existing Portfolio
      security:
        - oidc: [read:portfolio]
      description: Returns a single existing Portfolio, including Task Orders and Operators
      operationId: getPortfolioById
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
      responses:
        '200':
          description: Portfolio successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Portfolio'
        '400':
          description: Invalid ID supplied
        '404':
          description: Portfolio not found
    patch:
      tags:
        - access
      security:
        - oidc: [write:portfolio]
      description: >-
        Updates an existing Portfolio. Currently limited to the `administrators` attribute which will add
        administrators to an existing Portfolio. Note that this is a strictly additive operation; invitations
        should be sent to all email addresses included in a request. If an Operator included in this operation
        already has access to the Portfolio in the target Cloud Environment, their access should be reset
        (whether via a token, password or other vendor-specific means). It is expected that removal of access will occur
        through native CSP mechanisms rather than via ATAT.
      operationId: patchPortfolio
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
      responses:
        '200':
          description: Portfolio successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioPatch'
        '400':
          description: Invalid ID supplied
        '404':
          description: Portfolio not found
  '/portfolios/{portfolioId}/cost':
    get:
      tags:
        - cost
      summary: Returns cost data for a Portfolio, broken down by Task Order & CLINs
      security:
        - oidc: [read:cost]
      description: Queries CSP for actual or forecasted cost data across a Portfolio
      operationId: getCostsByPortfolio
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          description: Start date of the cost data request
          required: true
          schema:
            type: string
            format: date
            example: "2021-12-31"
        - name: end_date
          in: query
          description: End date of the cost data request
          required: true
          schema:
            type: string
            format: date
            example: "2026-12-31"
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
      responses:
        '200':
          description: Cost operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostResponseByPortfolio'
              examples:
                CostResponseActual:
                  $ref: '#/components/examples/CostResponseByPortfolio'
        '400':
          description: Invalid ID or query parameters
        '404':
          description: Portfolio not found
  '/portfolios/{portfolioId}/task-orders':
    post:
      tags:
        - provisioning
      summary: Adds a new Task Order (TO)
      security:
        - oidc: [write:portfolio]
      description: Adds a new Task Order to an existng Portfolio
      operationId: addTaskOrder
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskOrder'
        '400':
          description: Invalid ID supplied
        '404':
          description: Portfolio not found
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskOrder'
  '/portfolios/{portfolioId}/task-orders/{taskOrderNumber}/clins/{clin}/cost':
    get:
      tags:
        - cost
      summary: Returns cost data by Clin
      security:
        - oidc: [read:cost]
      description: Queries CSP for actual or forecasted cost data by Clin
      operationId: getCostsByClin
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: taskOrderNumber
          in: path
          description: task order number
          required: true
          schema:
            type: string
        - name: clin
          in: path
          description: contract line item number
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          description: Start date of the cost data request
          required: true
          schema:
            type: string
            format: date
            example: "2021-12-31"
        - name: end_date
          in: query
          description: End date of the cost data request
          required: true
          schema:
            type: string
            format: date
            example: "2026-12-31"
        - name: X-Target-Impact-Level
          description: >-
            Target Impact Level for this request. Optional header which allows an ATAT implementation to route a request to a
            more specific environment if more than one is available at a given endpoint.
          in: header
          schema:
            $ref: '#/components/schemas/ImpactLevel'
      responses:
        '200':
          description: Cost operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostResponseByClin'
              examples:
                CostResponseActual:
                  $ref: '#/components/examples/CostResponseByClin'
        '400':
          description: Invalid ID or query parameters
        '404':
          description: Portfolio not found
components:
  securitySchemes:
    oidc:
      description: >-
        Represents an OIDC configuration for an Identity Provider which will be managed by the ATAT Team. ATAT implementations should
        be configured to accept and validate tokens it.
      type: openIdConnect
      openIdConnectUrl: https://TBD/.well-known/openid-configuration
  schemas:
    ProvisioningStatus:
      type: object
      description: >-
        Represents the status of a provisioning job submitted via POST /portfolios
      properties:
        id:
          type: string
          description: The ID of the Provisioning job; used for retrieving status to inform end user
          example: "123456789"
        status:
          type: string
          enum:
            - "NOT_STARTED"
            - "IN_PROGRESS"
            - "COMPLETE"
            - "FAILED"
    PortfolioPatch:
      properties:
        administrators:
          type: array
          items:
            $ref: '#/components/schemas/Operator'
    Portfolio:
      allOf:
        - $ref: '#/components/schemas/PortfolioPatch'
      description: >-
        Logical container for a set of cloud resources which are paid for by a Task Order & its CLINS.
      required:
        - name
        - task_orders
        - administrators
      properties:
        name:
          type: string
          example: "Sample Portfolio name"
        task_orders:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/TaskOrder'
        id:
          description: >-
            Represents the unqiue ID of the Portfolio created by the vendor. In order to enable the ATAT UI to construct links back to the
            provisioned environment, this should be the same ID generated internally for the vendor's Portfolio-equivalent construct.
          type: string
          readOnly: true
          example: "csp-portfolio-id-123"
        dashboard_link:
          description: >-
            Represents a deep link to the Portfolio as represented in the vendor's dashboard. Allows ATAT to provide direct links to
            a Mission Owner's Portfolio within the vendor's environment.
          type: string
          format: uri
          example: "https://vendor.com/account/csp-portfolio-id-123"
    TaskOrder:
      type: object
      description: >-
        A Task Order and CLINs used to pay for provisioned resources and services
      required:
        - task_order_number
        - clins
        - pop_start_date
        - pop_end_date
      properties:
        task_order_number:
          type: string
          example: "1234567891234"
        clins:
          type: array
          items:
            $ref: '#/components/schemas/Clin'
        pop_start_date:
          description: Start of period of performance (for this Task Order)
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          description: End of period of performance (for this Task Order)
          type: string
          format: date
          example: "2026-07-01"
    Clin:
      description: Represents a CLIN in a Task Order
      additionalProperties: false
      properties:
        clin_number:
          description: Contract Line Item Number (CLIN), 0001 through 9999
          type: string
          pattern: '(?!^0{4}$)^\d{4}$'
        pop_start_date:
          description: Start of period of performance (for this CLIN)
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          description: End of period of performance (for this CLIN)
          type: string
          format: date
          example: "2022-07-01"
    Operator:
      description: >-
        Represents an individual who should have access to a Portfolio in a target Cloud Environment.
      properties:
        email:
          type: string
          format: email
          example: "portfolio.admin@mail.mil"
        dod_id:
          type: string
          minLength: 10
          maxLength: 10
        needs_reset:
          description: >-
            Flag which denotes whether the given Operator's access should be updated (password/token reset or other vendor-specific process)
          type: boolean
          default: false
    ImpactLevel:
      description: List of available Imapct Levels for target Cloud Environments
      type: string
      enum:
        - IL2
        - IL3
        - IL4
        - IL5
        - IL6
    CostResponseByClin:
      description: >-
        Provides cost data in a format in accordance with the provided CostRequest. For any time periods for which
        cost data has been generated, actual amounts should be provided. Otherwise, forecast data should be used
        instead.
      properties:
        actual:
          type: array
          items:
            $ref: '#/components/schemas/CostData'
        forecast:
          type: array
          items:
            $ref: '#/components/schemas/CostData'
    CostResponseByPortfolio:
      description: >-
        Provides cost data in a format in accordance with the provided CostRequest. For any time periods for which
        cost data has been generated, actual amounts should be provided. Otherwise, forecast data should be used
        instead. Broken down by each CLIN within each Task Order within the given Portfolio.
      properties:
        task_orders:
          type: array
          items:
            properties:
              task_order_number:
                type: string
              clins:
                type: array
                items:
                  properties:
                    clin_number:
                      type: string
                    actual:
                      type: array
                      items:
                        $ref: '#/components/schemas/CostData'
                    forecast:
                      type: array
                      items:
                        $ref: '#/components/schemas/CostData'
    CostData:
      properties:
        total:
          type: string
          description: Total cost (ACTUAL or FORECAST) for all included months in USD
          example: "12345.67"
        results:
          type: array
          items:
            properties:
              month:
                type: string
                example: "2022-12"
              value:
                type: string
                description: Cost (ACTUAL or FORECAST) for the given months in USD
  examples:
    CostResponseByClin:
      value:
        actual:
          total: "50.00"
          results:
            - month: "2021-10"
              value: "20.00"
            - month: "2021-11"
              value: "30.00"
    CostResponseByPortfolio:
      value:
        task_orders:
          - task_order_number: "1234567891234"
            clins:
              - clin_number: "0001"
                actual:
                  - total: "50.00"
                    results:
                      - month: "2021-12"
                        value: "20.00"
                      - month: "2022-01"
                        value: "30.00"
                forecast:
                  - total: "100.00"
                    results:
                      - month: "2022-02"
                        value: "100.00"
              - clin_number: "0002"
                actual:
                  - total: "750.00"
                    results:
                      - month: "2021-12"
                        value: "50.00"
                      - month: "2022-01"
                        value: "700.00"
                forecast:
                  - total: "1000.00"
                    results:
                      - month: "2022-02"
                        value: "100.00"
                      - month: "2022-03"
                        value: "900.00"
security:
  - oidc:
      - read:cost
      - read:portfolio
      - write:portfolio