openapi: 3.0.2
info:
  description: >-
    This is a DRAFT version of the API meant for provisioning resources into a JWCC Provider Cloud Environment. It will be
    implemented and maintained by all participating CSPs.
  version: 1.0.0-SNAPSHOT
  title: ATAT External API - Provisioning
  contact:
    email: atat-dev+provisioning_api@ccpo.mil
tags:
  - name: provisioning
    description: >-
      Portfolios represent a collection of related Applications under the purview of a
      Mission Owner.
  - name: cost
    description: >-
      Operations to query for actual and forecasted costs by Portfolio
paths:
  '/portfolios':
    post:
      tags:
        - provisioning
      summary: Adds a new Portfolio
      operationId: addPortfolio
      requestBody:
        description: A new Portfolio
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Portfolio'
      responses:
        '200':
          description: Portfolio fully provisioned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioResponse'
        '202':
          description: Portfolio provisioning request has been accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisioningStatus'
          headers:
            Location:
              description: Endpoint which ATAT should poll to receive status updates for this provisioning job
              schema:
                type: string
                example: https://csp.com/jwcc/provisioning/123456789/status
        '405':
          description: Invalid input
  '/portfolios/{portfolioId}':
    get:
      tags:
        - provisioning
      summary: Gets an existing Portfolio
      description: Returns a single Portfolio
      operationId: getPortfolioById
      parameters:
        - name: portfolioId
          in: path
          description: ID of the portfolio
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Portfolio successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Portfolio not found
  '/portfolios/{portfolioId}/cost':
    post:
      tags:
        - cost
      summary: Queries CSP for actual or forecasted cost data by Portfolio
      operationId: getCosts
      parameters:
        - name: portfolioId
          in: path
          description: ID of the portfolio
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CostRequest'
            examples:
              CostRequestActual:
                $ref: '#/components/examples/CostRequestActual'
      responses:
        '200':
          description: Cost operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostResponse'
              examples:
                CostResponseActual:
                  $ref: '#/components/examples/CostResponseActual'
        '400':
          description: Invalid ID supplied
        '404':
          description: Portfolio not found
  '/portfolios/{portfolioId}/applications/{applicationId}/environments/{environmentId}/operator-roles':
    post:
      tags:
        - provisioning
      summary: Assigns an Operator to a specific level of access in an Environment
      description: Assigns an Operator to a specific level of access in an Environment
      operationId: addOperatorRole
      parameters:
        - name: portfolioId
          in: path
          description: ID of the Portfolio
          required: true
          schema:
            type: string
        - name: applicationId
          in: path
          description: ID of the Application
          required: true
          schema:
            type: string
        - name: environmentId
          in: path
          description: ID of the Environment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperatorRole'
        '405':
          description: Invalid input
      requestBody:
        description: A new OperatorRole
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperatorRole'
components:
  schemas:
    ProvisioningStatus:
      type: object
      description: >-
        Represents the status of a provisioning job submitted via POST /portfolios
      properties:
        id:
          type: string
          description: The ID of the Provisioning job; used for retrieving status to inform end user
          example: 123456789
        status:
          type: string
          enum:
            - "NOT_STARTED"
            - "IN_PROGRESS"
            - "COMPLETE"
            - "FAILED"
    Portfolio:
      type: object
      description: >-
        Logical container for a set of cloud resources which are paid for by the same set of Funding Sources / Task Orders.
        Contains a set of Applications, each of which contain a set of Environments in turn, all of which should support
        independent management and access control.
      required:
        - name
      properties:
        name:
          type: string
          example: "Sample Portfolio name"
        funding_sources:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/FundingSource'
        applications:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Application'
    PortfolioResponse:
      allOf:
        - $ref: '#/components/schemas/Portfolio'
        - type: object
          properties:
            id:
              type: string
              example: "csp-portfolio-id-123"
            applications:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/ApplicationResponse'
    FundingSource:
      type: object
      description: >-
        A set of Task Orders and CLINs used to pay for JWCC resources.
      properties:
        task_order_number:
          type: string
          example: "1234567891234"
        clin:
          type: string
          example: "0001"
        pop_start_date:
          type: string
          format: date
          example: "2021-07-01"
        pop_end_date:
          type: string
          format: date
          example: "2022-07-01"
    Application:
      type: object
      description: >-
        Applications represent a set of Environments which make up a single
        application, system or set of related services as defined by a Mission
        Owner
      properties:
        name:
          type: string
          example: "Sample Application name"
        description:
          type: string
          example: "Sample Application description"
        environments:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Environment'
    ApplicationResponse:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: "csp-application-id-123"
            environments:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/EnvironmentResponse'
        - $ref: '#/components/schemas/Application'
    Environment:
      type: object
      description: >-
        Environments represent a grouping of cloud resources, organized by
        system usage (e.g. Production, Staging, Test, Dev, etc.)
      required:
        - name
      properties:
        name:
          type: string
          example: "Production"
        operator_roles:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/OperatorRole'
    EnvironmentResponse:
      allOf:
        - $ref: '#/components/schemas/Environment'
        - type: object
          properties:
            id:
              type: string
              example: "csp-environment-id-123"
    OperatorRole:
      type: object
      required:
        - operator_email
        - access
      properties:
        operator_email:
          type: string
          example: "user@mail.mil"
        access:
          type: string
          description: Operator Access Level to Environment
          enum:
            - administrator
            - read_only
    TimePeriod:
      type: object
      properties:
        start_date:
          type: string
          format: date
          example: "2021-10-01"
        end_date:
          type: string
          format: date
          example: "2021-12-01"
    CostRequest:
      type: object
      properties:
        period:
          $ref: '#/components/schemas/TimePeriod'
        granularity:
          type: string
          enum:
            - "MONTHLY"
            - "DAILY"
        type:
          type: string
          enum:
            - "ACTUAL"
            - "FORECAST"
    CostResponse:
      type: object
      properties:
        total:
          type: string
          description: Total cost (ACTUAL or FORECAST) for entire time period in USD
          example: "12345.6789"
        results:
          type: array
          items:
            properties:
              period:
                $ref: '#/components/schemas/TimePeriod'
              value:
                type: string
                description: Cost (ACTUAL or FORECAST) for the given time period in USD
  examples:
    CostRequestActual:
      value:
        period:
          start_date: "2021-10-01"
          end_date: "2021-12-01"
        granularity: "MONTHLY"
        type: "ACTUAL"
    CostResponseActual:
      value:
        total: "50.00"
        results:
          - period:
              start_date: "2021-10-01"
              end_date: "2021-11-01"
            value: "20.00"
          - period:
              start_date: "2021-11-01"
              end_date: "2021-12-01"
            value: "30.00"